# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a77d31c3fbc3ef677417f236aa2c6fa3fc078fb36565f0e57e44555feddcf70120a85027b2e235d3b8b00f8547c884af558088f19c49099202476b48e6c527f

test:
  secret_key_base: 1e72652f1fc2000f1bdb97e1ee84a76e2239763ee03135b8a7d78efbba35b9cbeda8a50ab4c9cf9bcf6718c082c13d5dceb66f081204ac7b4f9e4781034b3d23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
